version: '2'

services:
  gtsite-service:
    image: quay.io/geotrellis/gtsite-service
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - "${HOME}/.ivy2:/root/.ivy2"
      - "${HOME}/.m2:/root/.m2"
      - "${HOME}/.sbt:/root/.sbt"
  gtsite-static:
    image: quay.io/geotrellis/gtsite-static
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
